instance_name: RoomMap.org
database_configuration:
  server:
    host: 192.168.11.200
    port: 5432
  database_name: roommap
  credentials:
    username: roommap
    password: YzgONYqaMcQdtYl9eqrx
api_http_server:
  port: 9999
  compression: "true"