instance_name: RoomMap.org
database_configuration:
  server:
    host: postgresql
    port: 27017
  database_name: roommap
  credentials:
    username: root
    password: password
api_http_server:
  port: 80
  compression: "true"